weights: yolov5x.pt
cfg: ''
data: data/blackout.yaml
hyp: data/hyps/hyp.scratch-low.yaml
epochs: 100
batch_size: 112
imgsz: 324
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: null
image_weights: false
device: 0,1,2,3
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 8
project: blackout
name: blackout
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
seed: 0
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: blackout/blackout
